# this is a generated file, to avoid over-writing it just delete this comment
begin
  require 'jar_dependencies'
rescue LoadError
  require 'com/fasterxml/woodstox/woodstox-core/6.0.1/woodstox-core-6.0.1.jar'
  require 'org/apache/httpcomponents/httpcore/4.4.11/httpcore-4.4.11.jar'
  require 'org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar'
  require 'com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.10.0/jackson-module-jaxb-annotations-2.10.0.jar'
  require 'org/apache/olingo/odata-client-core/4.7.1/odata-client-core-4.7.1.jar'
  require 'org/slf4j/slf4j-simple/1.7.7/slf4j-simple-1.7.7.jar'
  require 'com/fasterxml/jackson/core/jackson-annotations/2.10.0/jackson-annotations-2.10.0.jar'
  require 'jakarta/activation/jakarta.activation-api/1.2.1/jakarta.activation-api-1.2.1.jar'
  require 'commons-logging/commons-logging/1.2/commons-logging-1.2.jar'
  require 'commons-codec/commons-codec/1.12/commons-codec-1.12.jar'
  require 'com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.10.0/jackson-dataformat-xml-2.10.0.jar'
  require 'org/apache/olingo/odata-commons-core/4.7.1/odata-commons-core-4.7.1.jar'
  require 'com/fasterxml/jackson/core/jackson-databind/2.10.0/jackson-databind-2.10.0.jar'
  require 'com/fasterxml/aalto-xml/0.9.11/aalto-xml-0.9.11.jar'
  require 'org/apache/olingo/odata-client-api/4.7.1/odata-client-api-4.7.1.jar'
  require 'commons-io/commons-io/2.6/commons-io-2.6.jar'
  require 'org/codehaus/woodstox/stax2-api/4.2/stax2-api-4.2.jar'
  require 'org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar'
  require 'org/apache/httpcomponents/httpclient/4.5.8/httpclient-4.5.8.jar'
  require 'com/fasterxml/jackson/core/jackson-core/2.10.0/jackson-core-2.10.0.jar'
  require 'jakarta/xml/bind/jakarta.xml.bind-api/2.3.2/jakarta.xml.bind-api-2.3.2.jar'
  require 'org/apache/olingo/odata-commons-api/4.7.1/odata-commons-api-4.7.1.jar'
end

if defined? Jars
  require_jar 'com.fasterxml.woodstox', 'woodstox-core', '6.0.1'
  require_jar 'org.apache.httpcomponents', 'httpcore', '4.4.11'
  require_jar 'org.apache.commons', 'commons-lang3', '3.9'
  require_jar 'com.fasterxml.jackson.module', 'jackson-module-jaxb-annotations', '2.10.0'
  require_jar 'org.apache.olingo', 'odata-client-core', '4.7.1'
  require_jar 'org.slf4j', 'slf4j-simple', '1.7.7'
  require_jar 'com.fasterxml.jackson.core', 'jackson-annotations', '2.10.0'
  require_jar 'jakarta.activation', 'jakarta.activation-api', '1.2.1'
  require_jar 'commons-logging', 'commons-logging', '1.2'
  require_jar 'commons-codec', 'commons-codec', '1.12'
  require_jar 'com.fasterxml.jackson.dataformat', 'jackson-dataformat-xml', '2.10.0'
  require_jar 'org.apache.olingo', 'odata-commons-core', '4.7.1'
  require_jar 'com.fasterxml.jackson.core', 'jackson-databind', '2.10.0'
  require_jar 'com.fasterxml', 'aalto-xml', '0.9.11'
  require_jar 'org.apache.olingo', 'odata-client-api', '4.7.1'
  require_jar 'commons-io', 'commons-io', '2.6'
  require_jar 'org.codehaus.woodstox', 'stax2-api', '4.2'
  require_jar 'org.slf4j', 'slf4j-api', '1.7.7'
  require_jar 'org.apache.httpcomponents', 'httpclient', '4.5.8'
  require_jar 'com.fasterxml.jackson.core', 'jackson-core', '2.10.0'
  require_jar 'jakarta.xml.bind', 'jakarta.xml.bind-api', '2.3.2'
  require_jar 'org.apache.olingo', 'odata-commons-api', '4.7.1'
end
